# Generated by Django 5.2 on 2025-04-29 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=150, verbose_name='E-mail')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Altura (m)')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Estado')),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla do Estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('numero_cartao', models.CharField(max_length=16, verbose_name='Número do Cartão')),
                ('nome_titular', models.CharField(max_length=255, verbose_name='Nome no Cartão')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('cvv', models.CharField(max_length=3, verbose_name='CVV')),
                ('bandeira_cartao', models.CharField(max_length=20, verbose_name='Bandeira do Cartão')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'db_table': 'cartoes_credito',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.estado', verbose_name='Estado de residência'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('forma_pagamento', models.CharField(choices=[('C', 'Cartão de Crédito'), ('P', 'PIX')], max_length=1, verbose_name='Forma de Pagamento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('cartao_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.cartaocredito', verbose_name='Cartão de Crédito')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planos.plano', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'matriculas',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Município')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.estado', verbose_name='Estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.municipio', verbose_name='Município de residência'),
        ),
    ]
