# Generated by Django 5.2 on 2025-05-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='forma_pagamento',
            field=models.CharField(choices=[('C', 'Cartão de Crédito'), ('P', 'PIX'), ('D', 'Débito')], max_length=1, verbose_name='Forma de Pagamento'),
        ),
    ]
