# Generated by Django 5.2 on 2025-05-20 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_matricula_forma_pagamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartaoCredito',
            new_name='Cartao',
        ),
        migrations.AlterModelOptions(
            name='cartao',
            options={'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='cartao_credito',
        ),
        migrations.AddField(
            model_name='matricula',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.cartao', verbose_name='Cartão'),
        ),
        migrations.AlterModelTable(
            name='cartao',
            table='cartoes',
        ),
    ]
