# Generated by Django 5.2 on 2025-05-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_rename_cartaocredito_cartao_alter_cartao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='data_validade',
            field=models.CharField(max_length=7, verbose_name='Data de Validade (AAAA/MM)'),
        ),
    ]
