# Generated by Django 5.2 on 2025-05-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_cartao_data_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='bandeira_cartao',
            field=models.CharField(choices=[('M', 'Mastecard'), ('V', 'Visa'), ('E', 'Elo')], max_length=10, verbose_name='Bandeira de Cartao'),
        ),
    ]
