# Generated by Django 5.2 on 2025-05-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado',
            field=models.CharField(choices=[('P', 'Paraná'), ('S', 'São Paulo'), ('G', 'Goiânia')], max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.CharField(choices=[('P', 'Paraná'), ('S', 'São Paulo'), ('G', 'Goiânia')], max_length=40, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
