# Generated by Django 5.2 on 2025-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_aluno_estado_alter_municipio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado',
            field=models.CharField(choices=[('PR', 'Paraná'), ('SP', 'São Paulo'), ('GO', 'Goiânia'), ('DF', 'Distrito Federal')], max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.CharField(choices=[('PR', 'Paraná'), ('SP', 'São Paulo'), ('GO', 'Goiânia'), ('DF', 'Distrito Federal')], max_length=40, verbose_name='Estado'),
        ),
    ]
