# Generated by Django 5.2 on 2025-05-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_aluno_estado_alter_municipio_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='estado',
        ),
    ]
