# Generated by Django 5.2 on 2025-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_remove_aluno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.CharField(choices=[('SC', 'Santa Catarina'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('PR', 'Paraná'), ('SP', 'São Paulo'), ('GO', 'Goiânia'), ('DF', 'Distrito Federal')], max_length=40, verbose_name='Estado'),
        ),
    ]
