# Generated by Django 5.2 on 2025-05-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(max_length=255, verbose_name='Categoria')),
                ('equipamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
