# Generated by Django 5.2 on 2025-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade',
            name='categoria',
            field=models.CharField(choices=[('M', 'Musculação'), ('D', 'Dança'), ('G', 'Ginástica')], max_length=255, verbose_name='Categoria'),
        ),
    ]
