# Generated by Django 5.2 on 2025-04-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0002_alter_modalidade_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidade',
            name='nome',
        ),
    ]
