# Generated by Django 5.2 on 2025-04-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0003_remove_modalidade_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade',
            name='categoria',
            field=models.CharField(choices=[('Musculação', 'Musculacao'), ('Dança', 'Danca'), ('Ginástica', 'Ginastica')], max_length=255, verbose_name='Categoria'),
        ),
    ]
