# Generated by Django 5.2 on 2025-05-05 19:18

from django.db import migrations, models

def definir_tipos_planos(apps, schema_editor):
    Plano = apps.get_model('planos', 'Plano')
    Plano.objects.filter(nome__icontains='dumbbell').update(tipo='DUMBBELL')
    Plano.objects.exclude(nome__icontains='dumbbell').update(tipo='STARTER')

class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0005_alter_modalidade_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='nome',
            field=models.CharField(default='', max_length=255, verbose_name='Nome'),
        ),



    ]
