# Generated by Django 5.2 on 2025-05-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0006_modalidade_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidade',
            name='nome',
        ),
    ]
