# Generated by Django 5.2 on 2025-04-29 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('objetivo', models.CharField(choices=[('H', 'Hipertrofia'), ('F', 'Forca'), ('R', 'Resistencia'), ('E', 'Emagrecimento'), ('X', 'Flexibilidade')], max_length=1, verbose_name='Objetivo')),
                ('disponibilidade', models.CharField(max_length=1, verbose_name='Disponibilidade')),
                ('observacao', models.TextField(verbose_name='Observações')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.aluno', verbose_name='Aluno')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
