# Generated by Django 5.2 on 2025-05-24 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('objetivo', models.CharField(choices=[('H', 'Hipertrofia'), ('F', 'Forca'), ('R', 'Resistencia'), ('E', 'Emagrecimento'), ('X', 'Flexibilidade')], max_length=1, verbose_name='Objetivo')),
                ('disponibilidade', models.CharField(max_length=1, verbose_name='Disponibilidade')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.aluno', verbose_name='Aluno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExercicioTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('series', models.PositiveIntegerField(default=None, verbose_name='Número de séries')),
                ('repeticoes', models.PositiveIntegerField(default=None, verbose_name='Número de repetições')),
                ('carga', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descanso', models.PositiveIntegerField(default=90, help_text='Informe o tempo de descanso em segundos', verbose_name='Tempo de descanso (em segundos)')),
                ('exercicio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='exercicio', to='exercicios.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treino', to='treinos.treino')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
