# Generated by Django 5.2 on 2025-05-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_aluno_user'),
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.CreateModel(
            name='ExercicioTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.treino', verbose_name='Treino')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
