# Generated by Django 5.2 on 2025-05-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciotreino',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercicios.exercicio'),
        ),
        migrations.AlterField(
            model_name='exerciciotreino',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='treinos.treino'),
        ),
    ]
