# Generated by Django 5.2 on 2025-05-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
        ('treinos', '0002_alter_treino_aluno_exerciciotreino'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciciotreino',
            name='carga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exerciciotreino',
            name='descanso',
            field=models.PositiveIntegerField(default=90, help_text='Informe o tempo de descanso em segundos', verbose_name='Tempo de descanso (em segundos)'),
        ),
        migrations.AddField(
            model_name='exerciciotreino',
            name='exercicio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='exercicios.exercicio'),
        ),
        migrations.AddField(
            model_name='exerciciotreino',
            name='repeticoes',
            field=models.PositiveIntegerField(default=None, verbose_name='Número de repetições'),
        ),
        migrations.AddField(
            model_name='exerciciotreino',
            name='series',
            field=models.PositiveIntegerField(default=None, verbose_name='Número de séries'),
        ),
        migrations.AlterField(
            model_name='exerciciotreino',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='treinos.treino'),
        ),
    ]
